version: "3.10"
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=nineint
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=NqruPHs8eIXezIPmyiZJLfpRNqyLj9QlCoUhma5Aq9KOS5uWTPgAwIn3KUNdFko5
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nineint

    volumes:
      - postgres-db:/var/lib/postgresql/data
    
volumes:
    postgres-db: